project:
  type: website
  output-dir: docs

website:
  title: "OPERA Initiative"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: mission.qmd
        text: Mission
      - href: principles.qmd
        text: Basic Principles
      - href: projects.qmd
        text: Projects
      - href: publications.qmd
        text: Publications
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true